project_id = "ytgalgzikozeumomflhp"

[functions.instagram-webhook]
verify_jwt = false

[functions.process-ocr]
verify_jwt = false

[functions.google-auth]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false