// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytgalgzikozeumomflhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Z2FsZ3ppa296ZXVtb21mbGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Nzg3NzksImV4cCI6MjA3MjI1NDc3OX0.o9UvXKMAkFCJYkrTbUq2sn4EJTjYvQ0YuohR1oOm88Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});